"""inicial

Revision ID: 158d6ba23d37
Revises: 
Create Date: 2021-03-25 11:54:28.031894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '158d6ba23d37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='task')
    op.drop_table('task')
    op.create_unique_constraint(None, 'product', ['name'])
    op.add_column('usuario', sa.Column('tarjeta', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'tarjeta')
    op.drop_constraint(None, 'product', type_='unique')
    op.create_table('task',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=70), nullable=True),
    sa.Column('image', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tax', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'task', ['name'], unique=True)
    # ### end Alembic commands ###
